language: ruby
rvm:
  - "1.9.3"
before_script:
  - "cp config/database.example.yml config/database.yml"
  - "bundle exec rake db:test:prepare"
script: bundle exec rspec
branches:
  only:
    - master
    - development